namespace ScrabbleScorer.Core.Enums;

public enum Letter
{
    Blank,
    E,
    A,
    I,
    O,
    N,
    R,
    T,
    L,
    S,
    U,
    D,
    G,
    B,
    C,
    M,
    P,
    F,
    H,
    V,
    W,
    Y,
    K,
    J,
    X,
    Q,
    Z
}

public static class LetterHelper
{
    public static readonly char[] AllLetters =
    {
        '_',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z'
    };
}

public static class LetterExtensions
{
    public static char ToChar(this Letter letter)
    {
        return letter switch
        {
            Letter.A => 'A',
            Letter.B => 'B',
            Letter.C => 'C',
            Letter.D => 'D',
            Letter.E => 'E',
            Letter.F => 'F',
            Letter.G => 'G',
            Letter.H => 'H',
            Letter.I => 'I',
            Letter.J => 'J',
            Letter.K => 'K',
            Letter.L => 'L',
            Letter.M => 'M',
            Letter.N => 'N',
            Letter.O => 'O',
            Letter.P => 'P',
            Letter.Q => 'Q',
            Letter.R => 'R',
            Letter.S => 'S',
            Letter.T => 'T',
            Letter.U => 'U',
            Letter.V => 'V',
            Letter.W => 'W',
            Letter.X => 'X',
            Letter.Y => 'Y',
            Letter.Z => 'Z',
            Letter.Blank => throw new Exception("Unable to convert blank to char"),
            _ => throw new ArgumentOutOfRangeException(nameof(letter), letter, null)
        };
    }

    public static Letter ToLetter(this char letter) =>
        letter switch
        {
            '_' => Letter.Blank,
            'A' => Letter.A,
            'B' => Letter.B,
            'C' => Letter.C,
            'D' => Letter.D,
            'E' => Letter.E,
            'F' => Letter.F,
            'G' => Letter.G,
            'H' => Letter.H,
            'I' => Letter.I,
            'J' => Letter.J,
            'K' => Letter.K,
            'L' => Letter.L,
            'M' => Letter.M,
            'N' => Letter.N,
            'O' => Letter.O,
            'P' => Letter.P,
            'Q' => Letter.Q,
            'R' => Letter.R,
            'S' => Letter.S,
            'T' => Letter.T,
            'U' => Letter.U,
            'V' => Letter.V,
            'W' => Letter.W,
            'X' => Letter.X,
            'Y' => Letter.Y,
            'Z' => Letter.Z,
            'a' => Letter.A,
            'b' => Letter.B,
            'c' => Letter.C,
            'd' => Letter.D,
            'e' => Letter.E,
            'f' => Letter.F,
            'g' => Letter.G,
            'h' => Letter.H,
            'i' => Letter.I,
            'j' => Letter.J,
            'k' => Letter.K,
            'l' => Letter.L,
            'm' => Letter.M,
            'n' => Letter.N,
            'o' => Letter.O,
            'p' => Letter.P,
            'q' => Letter.Q,
            'r' => Letter.R,
            's' => Letter.S,
            't' => Letter.T,
            'u' => Letter.U,
            'v' => Letter.V,
            'w' => Letter.W,
            'x' => Letter.X,
            'y' => Letter.Y,
            'z' => Letter.Z,
            _ => throw new ArgumentOutOfRangeException(nameof(letter), letter, null)
        };

    public static int ToLetterValue(this char letter) =>
        letter switch
        {
            '_' => 0,
            'A' => 1,
            'B' => 3,
            'C' => 3,
            'D' => 2,
            'E' => 1,
            'F' => 4,
            'G' => 2,
            'H' => 4,
            'I' => 1,
            'J' => 8,
            'K' => 5,
            'L' => 1,
            'M' => 3,
            'N' => 1,
            'O' => 1,
            'P' => 3,
            'Q' => 10,
            'R' => 1,
            'S' => 1,
            'T' => 1,
            'U' => 1,
            'V' => 4,
            'W' => 4,
            'X' => 8,
            'Y' => 4,
            'Z' => 10,
            _ => throw new ArgumentOutOfRangeException(nameof(letter), letter, null)
        };
}
